name: Vulnerability Tracking

on:
  workflow_dispatch:
  schedule:
    # Runs every Wednesday at 12:00 UTC
    - cron: '0 12 * * 3'

permissions:
  actions: read

jobs:
  vulnlog:
    runs-on: ubuntu-latest
    steps:

      - name: Check out project
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'gradle'

      - name: Generate Vulnlog suppression files
        run: ./gradlew generateSuppression

      - name: Archive Vulnlog suppression files
        uses: actions/upload-artifact@v4
        with:
          name: vulnlog-suppression-files
          path: |
            build/vulnlog-suppressions/

  owaspDependencyCheck:
    needs: vulnlog
    runs-on: ubuntu-latest
    steps:

      - name: Check out project
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'gradle'

      - name: Download Vulnlog suppression files
        uses: actions/download-artifact@v4
        with:
          name: vulnlog-suppression-files
          path: build/vulnlog-suppressions/

      - name: Analyze project with OWASP Dependency Check
        env:
          OWASP_DEPENDENCY_CHECK_API_KEY: ${{ secrets.OWASP_DEPENDENCY_CHECK_API_KEY }}
        run: ./gradlew dependencyCheckAnalyze

      - name: Archive OWASP Dependency Check report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: |
            build/reports/dependency-check-report.html

  snykOpenSource:
    needs: vulnlog
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: read
      security-events: write

    steps:

      - name: Check out project
        uses: actions/checkout@v4

      - name: Download Vulnlog suppression files
        uses: actions/download-artifact@v4
        with:
          name: vulnlog-suppression-files
          path: build/vulnlog-suppressions/

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: 'gradle'

      - name: Copy generated Snyk suppression file to to the working directory
        run: cp build/vulnlog-suppressions/snyk-release-branch-2.yml .snyk

      - name: Analyze project with Snyk Open Source
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_KEY }}
        run: ./gradlew snyk-test

      - name: Archive Snyk reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: |
            build/reports/snyk.json
            build/reports/snyk.sarif

      - name: Upload Snyk SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: build/reports/snyk.sarif
          category: snyk-open-source
